import type { Config } from "../../loader/schema.js";

export function generateStandaloneHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ${config.name} v${config.version}
#  ${config.description ?? "Self-contained interactive installer"}
#
#  Generated by dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}
