import type { Config } from "../../loader/schema.js";
import { headerCommentLine, standaloneDescription } from "../header-metadata.js";

export function generateStandaloneHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${headerCommentLine(`${config.name} v${config.version}`)}
${headerCommentLine(standaloneDescription(config))}
#
#  Generated by dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}
