import fs from "node:fs";
import path from "node:path";
import type { MenuItem, Config } from "../loader/schema.js";
import { flattenNodes, topoSort } from "../utils/deps.js";
import { loadTemplate, renderTemplate } from "./template.js";

export interface AssembleOptions {
  config: Config;
  configPath: string;
  selectedIds: Set<string>;
}

/**
 * Assemble a complete shell script from selected menu items.
 */
export function assemble(opts: AssembleOptions): string {
  const { config, configPath, selectedIds } = opts;
  const allNodes = flattenNodes(config.menu);
  const configDir = path.dirname(path.resolve(configPath));

  // Topological sort for correct dependency order
  const sortedIds = topoSort(selectedIds, allNodes);

  const sections: string[] = [];

  // Header
  sections.push(generateHeader(config));

  // Global vars from config
  if (config.vars && Object.keys(config.vars).length > 0) {
    sections.push("# Global variables");
    for (const [key, val] of Object.entries(config.vars)) {
      sections.push(`${key}="${val}"`);
    }
    sections.push("");
  }

  // Each selected script
  for (const id of sortedIds) {
    const node = allNodes.get(id)!;
    if (!node.script) continue;

    const scriptPath = path.isAbsolute(node.script)
      ? node.script
      : path.resolve(configDir, node.script);

    const mergedVars = { ...config.vars, ...node.vars };
    const scriptContent = loadTemplate(scriptPath, mergedVars);

    sections.push(`# ─── ${node.label} (${node.id}) ───`);
    sections.push(scriptContent);
    sections.push("");
  }

  // Footer
  sections.push(generateFooter(config));

  return sections.join("\n");
}

function generateHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ${config.name} v${config.version}
#  ${config.description ?? "Auto-generated configuration script"}
#
#  Generated by dot - https://github.com/user/dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -euo pipefail

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
NC='\\033[0m'

log_info()  { echo -e "\${CYAN}[INFO]\${NC}  \$*"; }
log_ok()    { echo -e "\${GREEN}[OK]\${NC}    \$*"; }
log_warn()  { echo -e "\${YELLOW}[WARN]\${NC}  \$*"; }
log_error() { echo -e "\${RED}[ERROR]\${NC} \$*"; }

check_root() {
  if [ "\$(id -u)" -ne 0 ]; then
    log_error "请使用 root 或 sudo 运行此脚本"
    exit 1
  fi
}

`;
}

function generateFooter(config: Config): string {
  return `
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
log_ok "${config.name} 配置完成!"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}
