import path from "node:path";
import type { Config, MenuItem } from "../loader/schema.js";
import { flattenNodes, topoSort } from "../utils/deps.js";
import { headerCommentLine, legacyDescription } from "./header-metadata.js";
import { loadTemplate, resolveTemplatePath } from "./template.js";

export interface AssembleOptions {
  config: Config;
  configPath: string;
  selectedIds: Set<string>;
  /** Pre-computed flat node map (avoids redundant flattenNodes calls) */
  allNodes?: Map<string, MenuItem>;
  /** If provided, collects warnings (e.g. unresolved template variables) */
  warnings?: string[];
}

/**
 * Assemble a complete shell script from selected menu items.
 */
export function assemble(opts: AssembleOptions): string {
  const { config, configPath, selectedIds } = opts;
  const allNodes = opts.allNodes ?? flattenNodes(config.menu);
  const configDir = path.dirname(path.resolve(configPath));

  // Topological sort for correct dependency order
  const sortedIds = topoSort(selectedIds, allNodes);

  // Split into normal and post nodes
  const normalIds = sortedIds.filter((id) => !allNodes.get(id)?.post);
  const postIds = sortedIds.filter((id) => allNodes.get(id)?.post);

  const sections: string[] = [];

  // Header
  sections.push(generateHeader(config));

  // Global vars from config
  if (config.vars && Object.keys(config.vars).length > 0) {
    sections.push("# Global variables");
    for (const [key, val] of Object.entries(config.vars)) {
      sections.push(`${key}=${shellQuote(val)}`);
    }
    sections.push("");
  }

  // Render script sections
  const unresolved = new Set<string>();
  const renderSection = (id: string) => {
    const node = allNodes.get(id)!;
    if (!node.script) return;

    const scriptPath = resolveTemplatePath(node.script, configDir);

    const mergedVars = { ...config.vars, ...node.vars };
    const scriptContent = loadTemplate(scriptPath, mergedVars, unresolved);

    sections.push(`# ─── ${node.label} (${node.id}) ───`);
    sections.push(scriptContent);
    sections.push("");
  };

  normalIds.forEach(renderSection);
  postIds.forEach(renderSection);

  // Footer
  sections.push(generateFooter(config));

  // Collect warnings
  if (unresolved.size > 0 && opts.warnings) {
    opts.warnings.push(`Unresolved template variables: ${[...unresolved].join(", ")}`);
  }

  return sections.join("\n");
}

/** Escape special chars for use inside bash double quotes */
function shellEscapeChars(val: string): string {
  return val.replace(/["$`\\]/g, "\\$&");
}

/** Escape and wrap in double quotes for shell assignment */
function shellQuote(val: string): string {
  return `"${shellEscapeChars(val)}"`;
}

function generateHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${headerCommentLine(`${config.name} v${config.version}`)}
${headerCommentLine(legacyDescription(config))}
#
#  Generated by dot - https://github.com/user/dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -euo pipefail

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
NC='\\033[0m'

log_info()  { echo -e "\${CYAN}[INFO]\${NC}  \$*"; }
log_ok()    { echo -e "\${GREEN}[OK]\${NC}    \$*"; }
log_warn()  { echo -e "\${YELLOW}[WARN]\${NC}  \$*"; }
log_error() { echo -e "\${RED}[ERROR]\${NC} \$*"; }

`;
}

function generateFooter(config: Config): string {
  return `
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
log_ok "${shellEscapeChars(config.name)} 配置完成!"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}
