import path from "node:path";
import type { Config, MenuItem } from "../loader/schema.js";
import { flattenNodes, getLeafIds } from "../utils/deps.js";
import { loadTemplate } from "./template.js";

export interface StandaloneAssembleOptions {
  config: Config;
  configPath: string;
  allNodes?: Map<string, MenuItem>;
  warnings?: string[];
}

const ROOT_ID = "__root";

export function assembleStandalone(opts: StandaloneAssembleOptions): string {
  const { config, configPath } = opts;
  const allNodes = opts.allNodes ?? flattenNodes(config.menu);
  const configDir = path.dirname(path.resolve(configPath));

  for (const id of allNodes.keys()) {
    assertShellSafeId(id);
  }

  const snippetFunctions = new Map<string, string>();
  for (const [id, node] of allNodes) {
    if (node.script) {
      snippetFunctions.set(id, bashFunctionNameForId(id));
    }
  }

  const unresolved = new Set<string>();
  const sections = [
    generateHeader(config),
    generateRuntime(),
    generateData(config, allNodes, snippetFunctions),
    generateSnippetFunctions(config, configDir, allNodes, snippetFunctions, unresolved),
    'dot_main "$@"',
    "",
  ];

  if (unresolved.size > 0 && opts.warnings) {
    opts.warnings.push(`Unresolved template variables: ${[...unresolved].join(", ")}`);
  }

  return sections.join("\n");
}

export function bashFunctionNameForId(id: string): string {
  const safe = id.replace(/[^A-Za-z0-9_]/g, "_").replace(/^[0-9]/, "_$&");
  return `dot_run_${safe}_${stableHash(id)}`;
}

function stableHash(value: string): string {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

function assertShellSafeId(id: string): void {
  if (!/^[A-Za-z0-9_-]+$/.test(id)) {
    throw new Error(`Menu item id "${id}" is not shell-safe. Use only letters, digits, "_", and "-".`);
  }
}

function bashQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function assocAssign(name: string, key: string, value: string): string {
  return `${name}[${bashQuote(key)}]=${bashQuote(value)}`;
}

function generateHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ${config.name} v${config.version}
#  ${config.description ?? "Self-contained interactive installer"}
#
#  Generated by dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}

function generateRuntime(): string {
  return `set -uo pipefail

if [[ -z "@{BASH_VERSION:-}" ]]; then
  echo "This script requires bash." >&2
  exit 1
fi

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
BOLD='\\033[1m'
DIM='\\033[2m'
NC='\\033[0m'

log_info()  { printf "%b[INFO]%b  %s\\n" "$CYAN" "$NC" "$*"; }
log_ok()    { printf "%b[OK]%b    %s\\n" "$GREEN" "$NC" "$*"; }
log_warn()  { printf "%b[WARN]%b  %s\\n" "$YELLOW" "$NC" "$*"; }
log_error() { printf "%b[ERROR]%b %s\\n" "$RED" "$NC" "$*"; }

DOT_PLAN=()
DOT_POST_PLAN=()
declare -A DOT_SELECTED=()
declare -A DOT_PLAN_ADDED=()
declare -A DOT_RESULTS=()

restore_terminal() {
  printf '\\033[?25h'
}
trap restore_terminal EXIT INT TERM

dot_clear_screen() {
  if [[ -t 1 ]]; then
    printf '\\033[2J\\033[H'
  fi
}

dot_read_key() {
  local key seq
  IFS= read -rsn1 key || return 1
  if [[ "$key" == $'\\e' ]]; then
    IFS= read -rsn1 -t 0.05 seq 2>/dev/null || seq=""
    key+="$seq"
    IFS= read -rsn1 -t 0.05 seq 2>/dev/null || seq=""
    key+="$seq"
  fi
  printf '%s' "$key"
}

dot_pause() {
  printf "\\nPress any key to continue..."
  dot_read_key >/dev/null || true
}

dot_has_children() {
  local id="$1"
  [[ -n "@{DOT_CHILDREN[$id]:-}" ]]
}

dot_is_item_selected() {
  local id="$1"
  if [[ "@{DOT_SELECTED[$id]:-0}" == "1" ]]; then
    return 0
  fi

  if dot_has_children "$id"; then
    local leaf
    for leaf in @{DOT_LEAVES[$id]:-}; do
      if [[ "@{DOT_SELECTED[$leaf]:-0}" != "1" ]]; then
        return 1
      fi
    done
    return 0
  fi

  return 1
}

dot_toggle_item() {
  local id="$1"
  local leaves="@{DOT_LEAVES[$id]:-$id}"
  local leaf all_selected=1

  for leaf in $leaves; do
    if [[ "@{DOT_SELECTED[$leaf]:-0}" != "1" ]]; then
      all_selected=0
      break
    fi
  done

  if [[ "$all_selected" == "1" ]]; then
    unset "DOT_SELECTED[$id]"
    for leaf in $leaves; do
      unset "DOT_SELECTED[$leaf]"
    done
  else
    DOT_SELECTED[$id]=1
    for leaf in $leaves; do
      DOT_SELECTED[$leaf]=1
    done
  fi
}

dot_render_menu() {
  local current="$1" selected="$2"
  local -a items=()
  read -r -a items <<< "@{DOT_CHILDREN[$current]:-}"

  dot_clear_screen
  printf "%b%s%b\\n" "$BOLD" "@{DOT_LABELS[$current]:-$DOT_TITLE}" "$NC"
  if [[ -n "@{DOT_DESCRIPTIONS[$current]:-}" ]]; then
    printf "%b%s%b\\n" "$DIM" "@{DOT_DESCRIPTIONS[$current]}" "$NC"
  fi
  printf '%s\\n' "────────────────────────────────────────"

  local i id pointer mark arrow desc
  for i in "@{!items[@]}"; do
    id="@{items[$i]}"
    pointer=" "
    if [[ "$i" -eq "$selected" ]]; then
      pointer="@{CYAN}>@{NC}"
    fi

    mark=" "
    if dot_is_item_selected "$id"; then
      mark="x"
    fi

    arrow=""
    if dot_has_children "$id"; then
      arrow=" >"
    fi

    desc=""
    if [[ -n "@{DOT_DESCRIPTIONS[$id]:-}" ]]; then
      desc=" - @{DOT_DESCRIPTIONS[$id]}"
    fi

    printf " %b [%s] %s%s%b%s%b\\n" "$pointer" "$mark" "@{DOT_LABELS[$id]}" "$arrow" "$DIM" "$desc" "$NC"
  done

  printf '%s\\n' "────────────────────────────────────────"
  printf "%b↑/↓%b navigate  %bSpace%b select  %bEnter%b enter/toggle  %bb/←%b back  %bc%b confirm  %bq%b quit\\n" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC"
}

dot_add_with_deps() {
  local id="$1"
  if [[ "@{DOT_PLAN_ADDED[$id]:-0}" == "1" ]]; then
    return 0
  fi

  local dep
  for dep in @{DOT_DEPS[$id]:-}; do
    dot_add_with_deps "$dep"
  done

  DOT_PLAN_ADDED[$id]=1
  if [[ -n "@{DOT_SNIPPET_FUNCS[$id]:-}" ]]; then
    if [[ "@{DOT_POST[$id]:-0}" == "1" ]]; then
      DOT_POST_PLAN+=("$id")
    else
      DOT_PLAN+=("$id")
    fi
  fi
}

dot_build_plan() {
  DOT_PLAN=()
  DOT_POST_PLAN=()
  DOT_PLAN_ADDED=()

  local id leaf
  for id in "@{DOT_ALL_IDS[@]}"; do
    if [[ "@{DOT_SELECTED[$id]:-0}" != "1" ]]; then
      continue
    fi

    if dot_has_children "$id"; then
      for leaf in @{DOT_LEAVES[$id]:-}; do
        dot_add_with_deps "$leaf"
      done
    else
      dot_add_with_deps "$id"
    fi
  done

  DOT_PLAN+=("@{DOT_POST_PLAN[@]}")
}

dot_show_plan() {
  dot_clear_screen
  printf "%bExecution plan%b\\n" "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id index=1
  for id in "@{DOT_PLAN[@]}"; do
    if [[ "@{DOT_POST[$id]:-0}" == "1" ]]; then
      printf " %2d. %s %b(post)%b\\n" "$index" "@{DOT_LABELS[$id]}" "$DIM" "$NC"
    else
      printf " %2d. %s\\n" "$index" "@{DOT_LABELS[$id]}"
    fi
    index=$((index + 1))
  done

  printf '%s\\n' "────────────────────────────────────────"
}

dot_confirm_plan() {
  if [[ "@{#DOT_PLAN[@]}" -eq 0 ]]; then
    log_warn "No runnable items selected."
    dot_pause
    return 1
  fi

  dot_show_plan
  local answer
  printf "Execute this plan? [y/N] "
  read -r answer
  [[ "$answer" =~ ^[Yy]$ ]]
}

dot_navigate() {
  local current="__root"
  local -a stack=()
  local selected=0 key id

  while true; do
    local -a items=()
    read -r -a items <<< "@{DOT_CHILDREN[$current]:-}"
    if [[ "@{#items[@]}" -eq 0 ]]; then
      return 0
    fi

    if [[ "$selected" -ge "@{#items[@]}" ]]; then
      selected=0
    fi

    dot_render_menu "$current" "$selected"
    key="$(dot_read_key)" || return 1

    case "$key" in
      $'\\e[A')
        if [[ "$selected" -gt 0 ]]; then selected=$((selected - 1)); fi
        ;;
      $'\\e[B')
        if [[ "$selected" -lt $((@{#items[@]} - 1)) ]]; then selected=$((selected + 1)); fi
        ;;
      $'\\e[D'|b|B)
        if [[ "@{#stack[@]}" -gt 0 ]]; then
          current="@{stack[-1]}"
          unset 'stack[-1]'
          selected=0
        fi
        ;;
      " ")
        id="@{items[$selected]}"
        dot_toggle_item "$id"
        ;;
      "")
        id="@{items[$selected]}"
        if dot_has_children "$id"; then
          stack+=("$current")
          current="$id"
          selected=0
        else
          dot_toggle_item "$id"
        fi
        ;;
      c|C)
        dot_build_plan
        if dot_confirm_plan; then
          return 0
        fi
        ;;
      q|Q)
        return 1
        ;;
    esac
  done
}

dot_execute_plan() {
  dot_clear_screen
  printf "%bExecuting plan%b\\n" "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id func dep failed_dep status
  for id in "@{DOT_PLAN[@]}"; do
    failed_dep=0
    for dep in @{DOT_DEPS[$id]:-}; do
      if [[ "@{DOT_RESULTS[$dep]:-ok}" == "failed" || "@{DOT_RESULTS[$dep]:-ok}" == "skipped" ]]; then
        failed_dep=1
        break
      fi
    done

    if [[ "$failed_dep" == "1" ]]; then
      DOT_RESULTS[$id]="skipped"
      log_warn "Skipped @{DOT_LABELS[$id]} because a dependency failed"
      continue
    fi

    func="@{DOT_SNIPPET_FUNCS[$id]:-}"
    if [[ -z "$func" ]]; then
      continue
    fi

    log_info "Running @{DOT_LABELS[$id]}"
    "$func"
    status=$?
    if [[ "$status" -eq 0 ]]; then
      DOT_RESULTS[$id]="ok"
      log_ok "@{DOT_LABELS[$id]}"
    else
      DOT_RESULTS[$id]="failed"
      log_error "@{DOT_LABELS[$id]} failed with exit code $status"
    fi
  done
}

dot_print_summary() {
  printf '\\n%bSummary%b\\n' "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id status
  for id in "@{DOT_PLAN[@]}"; do
    status="@{DOT_RESULTS[$id]:-not-run}"
    case "$status" in
      ok) printf " %b✓%b %s\\n" "$GREEN" "$NC" "@{DOT_LABELS[$id]}" ;;
      skipped) printf " %b-%b %s (skipped)\\n" "$YELLOW" "$NC" "@{DOT_LABELS[$id]}" ;;
      *) printf " %b✗%b %s (%s)\\n" "$RED" "$NC" "@{DOT_LABELS[$id]}" "$status" ;;
    esac
  done
}

dot_main() {
  if ! dot_navigate; then
    printf '\\nAborted.\\n'
    exit 0
  fi

  dot_execute_plan
  dot_print_summary
}
`.replace(/@\{/g, "${");
}

function generateData(
  config: Config,
  allNodes: Map<string, MenuItem>,
  snippetFunctions: Map<string, string>
): string {
  const lines: string[] = [
    `DOT_TITLE=${bashQuote(config.name)}`,
    "declare -a DOT_ALL_IDS=(" + [...allNodes.keys()].map(bashQuote).join(" ") + ")",
    "declare -A DOT_LABELS=()",
    "declare -A DOT_DESCRIPTIONS=()",
    "declare -A DOT_CHILDREN=()",
    "declare -A DOT_DEPS=()",
    "declare -A DOT_LEAVES=()",
    "declare -A DOT_POST=()",
    "declare -A DOT_SNIPPET_FUNCS=()",
    assocAssign("DOT_LABELS", ROOT_ID, config.name),
    assocAssign("DOT_DESCRIPTIONS", ROOT_ID, config.description ?? ""),
    assocAssign("DOT_CHILDREN", ROOT_ID, config.menu.map((item) => item.id).join(" ")),
  ];

  for (const [id, node] of allNodes) {
    const children = node.children?.map((child) => child.id).join(" ") ?? "";
    const deps = node.deps?.join(" ") ?? "";
    const leaves = getLeafIds(node).join(" ");

    lines.push(assocAssign("DOT_LABELS", id, node.label));
    lines.push(assocAssign("DOT_DESCRIPTIONS", id, node.description ?? ""));
    lines.push(assocAssign("DOT_CHILDREN", id, children));
    lines.push(assocAssign("DOT_DEPS", id, deps));
    lines.push(assocAssign("DOT_LEAVES", id, leaves));
    lines.push(assocAssign("DOT_POST", id, node.post ? "1" : "0"));

    const func = snippetFunctions.get(id);
    if (func) {
      lines.push(assocAssign("DOT_SNIPPET_FUNCS", id, func));
    }
  }

  return lines.join("\n");
}

function generateSnippetFunctions(
  config: Config,
  configDir: string,
  allNodes: Map<string, MenuItem>,
  snippetFunctions: Map<string, string>,
  unresolved: Set<string>
): string {
  const sections: string[] = [];

  for (const [id, node] of allNodes) {
    const func = snippetFunctions.get(id);
    if (!func || !node.script) continue;

    const scriptPath = path.isAbsolute(node.script)
      ? node.script
      : path.resolve(configDir, node.script);
    const mergedVars = { ...config.vars, ...node.vars };
    const scriptContent = loadTemplate(scriptPath, mergedVars, unresolved).trimEnd();

    sections.push(`# ─── ${node.label} (${node.id}) ───`);
    sections.push(`${func}() {`);
    sections.push(scriptContent);
    sections.push("}");
  }

  return sections.join("\n\n");
}
