import path from "node:path";
import type { Config, MenuItem } from "../loader/schema.js";
import { flattenNodes, getLeafIds } from "../utils/deps.js";
import { loadTemplate } from "./template.js";

export interface StandaloneAssembleOptions {
  config: Config;
  configPath: string;
  allNodes?: Map<string, MenuItem>;
  warnings?: string[];
}

const ROOT_ID = "__root";

export function assembleStandalone(opts: StandaloneAssembleOptions): string {
  const { config, configPath } = opts;
  const allNodes = opts.allNodes ?? flattenNodes(config.menu);
  const configDir = path.dirname(path.resolve(configPath));

  for (const id of allNodes.keys()) {
    assertShellSafeId(id);
  }

  const snippetFunctions = new Map<string, string>();
  for (const [id, node] of allNodes) {
    if (node.script) {
      snippetFunctions.set(id, bashFunctionNameForId(id));
    }
  }

  const unresolved = new Set<string>();
  const sections = [
    generateHeader(config),
    generateRuntime(),
    generateData(config, allNodes, snippetFunctions),
    generateSnippetFunctions(config, configDir, allNodes, snippetFunctions, unresolved),
    'dot_main "$@"',
    "",
  ];

  if (unresolved.size > 0 && opts.warnings) {
    opts.warnings.push(`Unresolved template variables: ${[...unresolved].join(", ")}`);
  }

  return sections.join("\n");
}

export function bashFunctionNameForId(id: string): string {
  const safe = id.replace(/[^A-Za-z0-9_]/g, "_").replace(/^[0-9]/, "_$&");
  return `dot_run_${safe}_${stableHash(id)}`;
}

function stableHash(value: string): string {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

function assertShellSafeId(id: string): void {
  if (!/^[A-Za-z0-9_-]+$/.test(id)) {
    throw new Error(`Menu item id "${id}" is not shell-safe. Use only letters, digits, "_", and "-".`);
  }
}

function bashQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function assocAssign(name: string, key: string, value: string): string {
  return `${name}[${bashQuote(key)}]=${bashQuote(value)}`;
}

function generateHeader(config: Config): string {
  return `#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ${config.name} v${config.version}
#  ${config.description ?? "Self-contained interactive installer"}
#
#  Generated by dot
#  DO NOT EDIT - This file is auto-generated
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
}

function generateRuntime(): string {
  return `set -uo pipefail

if [[ -z "@{BASH_VERSION:-}" ]]; then
  echo "This script requires bash." >&2
  exit 1
fi

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
BOLD='\\033[1m'
DIM='\\033[2m'
NC='\\033[0m'

log_info()  { printf "%b[INFO]%b  %s\\n" "$CYAN" "$NC" "$*"; }
log_ok()    { printf "%b[OK]%b    %s\\n" "$GREEN" "$NC" "$*"; }
log_warn()  { printf "%b[WARN]%b  %s\\n" "$YELLOW" "$NC" "$*"; }
log_error() { printf "%b[ERROR]%b %s\\n" "$RED" "$NC" "$*"; }

DOT_PLAN=()
DOT_POST_PLAN=()
declare -A DOT_SELECTED=()
declare -A DOT_PLAN_ADDED=()
declare -A DOT_RESULTS=()
declare -A DOT_VARS=()

restore_terminal() {
  printf '\\033[?25h'
}
trap restore_terminal EXIT INT TERM

dot_clear_screen() {
  if [[ -t 1 ]]; then
    printf '\\033[2J\\033[H'
  fi
}

dot_read_key() {
  local key seq
  IFS= read -rsn1 key || return 1
  if [[ "$key" == $'\\e' ]]; then
    IFS= read -rsn1 -t 0.05 seq 2>/dev/null || seq=""
    key+="$seq"
    IFS= read -rsn1 -t 0.05 seq 2>/dev/null || seq=""
    key+="$seq"
  fi
  printf '%s' "$key"
}

dot_pause() {
  printf "\\nPress any key to continue..."
  dot_read_key >/dev/null || true
}


dot_key_to_tmux() {
  local key="$1"
  case "$key" in
    $'\x01') printf 'C-a' ;;
    $'\x02') printf 'C-b' ;;
    $'\x03') printf 'C-c' ;;
    $'\x04') printf 'C-d' ;;
    $'\x05') printf 'C-e' ;;
    $'\x06') printf 'C-f' ;;
    $'\x07') printf 'C-g' ;;
    $'\x08') printf 'C-h' ;;
    $'\x09') printf 'C-i' ;;
    $'\x0a') printf 'C-j' ;;
    $'\x0b') printf 'C-k' ;;
    $'\x0c') printf 'C-l' ;;
    $'\x0d') printf 'C-m' ;;
    $'\x0e') printf 'C-n' ;;
    $'\x0f') printf 'C-o' ;;
    $'\x10') printf 'C-p' ;;
    $'\x11') printf 'C-q' ;;
    $'\x12') printf 'C-r' ;;
    $'\x13') printf 'C-s' ;;
    $'\x14') printf 'C-t' ;;
    $'\x15') printf 'C-u' ;;
    $'\x16') printf 'C-v' ;;
    $'\x17') printf 'C-w' ;;
    $'\x18') printf 'C-x' ;;
    $'\x19') printf 'C-y' ;;
    $'\x1a') printf 'C-z' ;;
    $'\e') printf 'Escape' ;;
    $'\e[A') printf 'Up' ;;
    $'\e[B') printf 'Down' ;;
    $'\e[C') printf 'Right' ;;
    $'\e[D') printf 'Left' ;;
    *) printf '%s' "$key" ;;
  esac
}

dot_record_key_prompt() {
  local item="$1" var="@{DOT_PROMPT_VARS[$item]:-}" label="@{DOT_PROMPT_LABELS[$item]:-Press a key}"
  local key value

  while true; do
    dot_render_header "@{DOT_LABELS[$item]}" "$label"
    printf '%s\n' "────────────────────────────────────────"
    printf "请直接按下你想要的组合键。按 b 返回。\n"
    key="$(dot_read_key)" || return 1
    if [[ "$key" == "b" || "$key" == "B" ]]; then
      return 2
    fi
    value="$(dot_key_to_tmux "$key")"

    dot_render_header "@{DOT_LABELS[$item]}" "$label"
    printf '%s\n' "────────────────────────────────────────"
    printf "录制结果：%b%s%b\n\n" "$GREEN" "$value" "$NC"
    printf "Enter 确认，r 重新录制，b 返回："
    key="$(dot_read_key)" || return 1
    case "$key" in
      "")
        if [[ -n "$var" ]]; then
          DOT_VARS[$var]="$value"
        fi
        return 0
        ;;
      r|R) continue ;;
      b|B) return 2 ;;
    esac
  done
}

dot_visible_children() {
  local parent="$1" child out=()
  for child in @{DOT_CHILDREN[$parent]:-}; do
    if [[ "@{DOT_HIDDEN[$child]:-0}" != "1" ]]; then
      out+=("$child")
    fi
  done
  printf '%s ' "@{out[@]}"
}

dot_has_children() {
  local id="$1"
  [[ -n "$(dot_visible_children "$id")" ]]
}

dot_is_item_selected() {
  local id="$1"
  if [[ "@{DOT_SELECTED[$id]:-0}" == "1" ]]; then
    return 0
  fi

  if [[ -n "@{DOT_LEAVES[$id]:-}" ]]; then
    local leaf any=0
    for leaf in @{DOT_LEAVES[$id]:-}; do
      if [[ "@{DOT_SELECTED[$leaf]:-0}" == "1" ]]; then
        any=1
      else
        return 1
      fi
    done
    [[ "$any" == "1" ]]
    return
  fi

  return 1
}

dot_select_single_item() {
  local current="$1" id="$2" sibling leaf
  for sibling in @{DOT_CHILDREN[$current]:-}; do
    unset "DOT_SELECTED[$sibling]"
    for leaf in @{DOT_LEAVES[$sibling]:-$sibling}; do
      unset "DOT_SELECTED[$leaf]"
    done
  done

  DOT_SELECTED[$id]=1
  for leaf in @{DOT_LEAVES[$id]:-$id}; do
    DOT_SELECTED[$leaf]=1
  done
}

dot_toggle_multi_item() {
  local id="$1"
  local leaves="@{DOT_LEAVES[$id]:-$id}"
  local leaf all_selected=1

  for leaf in $leaves; do
    if [[ "@{DOT_SELECTED[$leaf]:-0}" != "1" ]]; then
      all_selected=0
      break
    fi
  done

  if [[ "$all_selected" == "1" ]]; then
    unset "DOT_SELECTED[$id]"
    for leaf in $leaves; do
      unset "DOT_SELECTED[$leaf]"
    done
  else
    DOT_SELECTED[$id]=1
    for leaf in $leaves; do
      DOT_SELECTED[$leaf]=1
    done
  fi
}

dot_render_header() {
  local title="$1" subtitle="@{2:-}"
  dot_clear_screen
  printf "%b%s%b\\n" "$BOLD" "$title" "$NC"
  if [[ -n "$subtitle" ]]; then
    printf "%b%s%b\\n" "$DIM" "$subtitle" "$NC"
  fi
}

dot_render_flow_progress() {
  local flow="$1" current_step="$2"
  local steps=() step index=1 total=0 line=""
  read -r -a steps <<< "$(dot_visible_children "$flow")"
  total="@{#steps[@]}"

  printf "%b流程进度:%b " "$CYAN" "$NC"
  for step in "@{steps[@]}"; do
    if [[ "$step" == "$current_step" ]]; then
      line+="@{BOLD}@{DOT_LABELS[$step]}@{NC}"
    else
      line+="@{DOT_LABELS[$step]}"
    fi
    if [[ "$index" -lt "$total" ]]; then
      line+=" → "
    fi
    index=$((index + 1))
  done
  printf "%b\\n\\n" "$line"
}

dot_render_single_menu() {
  local current="$1" selected="$2" title="$3" subtitle="@{4:-}"
  local items=() i id pointer desc
  read -r -a items <<< "$(dot_visible_children "$current")"

  dot_render_header "$title" "$subtitle"
  printf '%s\\n' "────────────────────────────────────────"
  for i in "@{!items[@]}"; do
    id="@{items[$i]}"
    pointer=" "
    if [[ "$i" -eq "$selected" ]]; then pointer="@{CYAN}>@{NC}"; fi
    desc=""
    if [[ -n "@{DOT_DESCRIPTIONS[$id]:-}" ]]; then desc=" - @{DOT_DESCRIPTIONS[$id]}"; fi
    printf " %b %s%b%s%b\\n" "$pointer" "@{DOT_LABELS[$id]}" "$DIM" "$desc" "$NC"
  done
  printf '%s\\n' "────────────────────────────────────────"
  printf "%b↑/↓%b 选择  %bEnter%b 确认  %bb/←%b 返回  %bq%b 退出\\n" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC"
}

dot_render_multi_menu() {
  local current="$1" selected="$2" title="$3" subtitle="@{4:-}"
  local items=() i id pointer mark desc
  read -r -a items <<< "$(dot_visible_children "$current")"

  dot_render_header "$title" "$subtitle"
  printf '%s\\n' "────────────────────────────────────────"
  for i in "@{!items[@]}"; do
    id="@{items[$i]}"
    pointer=" "
    if [[ "$i" -eq "$selected" ]]; then pointer="@{CYAN}>@{NC}"; fi
    mark=" "
    if dot_is_item_selected "$id"; then mark="x"; fi
    desc=""
    if [[ -n "@{DOT_DESCRIPTIONS[$id]:-}" ]]; then desc=" - @{DOT_DESCRIPTIONS[$id]}"; fi
    printf " %b [%s] %s%b%s%b\\n" "$pointer" "$mark" "@{DOT_LABELS[$id]}" "$DIM" "$desc" "$NC"
  done
  printf '%s\\n' "────────────────────────────────────────"
  printf "%b↑/↓%b 选择  %bSpace%b 切换  %bEnter%b 下一步  %bb/←%b 返回  %bq%b 退出\\n" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC" "$CYAN" "$NC"
}

dot_choose_single() {
  local current="$1" title="$2" subtitle="@{3:-}"
  local selected=0 key items=() id

  while true; do
    read -r -a items <<< "$(dot_visible_children "$current")"
    if [[ "@{#items[@]}" -eq 0 ]]; then return 1; fi
    if [[ "$selected" -ge "@{#items[@]}" ]]; then selected=0; fi

    dot_render_single_menu "$current" "$selected" "$title" "$subtitle"
    key="$(dot_read_key)" || return 1

    case "$key" in
      $'\\e[A') if [[ "$selected" -gt 0 ]]; then selected=$((selected - 1)); fi ;;
      $'\\e[B') if [[ "$selected" -lt $((@{#items[@]} - 1)) ]]; then selected=$((selected + 1)); fi ;;
      $'\\e[D'|b|B) return 2 ;;
      q|Q) return 1 ;;
      "") id="@{items[$selected]}"; DOT_CHOICE="$id"; return 0 ;;
    esac
  done
}

dot_choose_multi() {
  local current="$1" title="$2" subtitle="@{3:-}"
  local selected=0 key items=() id

  while true; do
    read -r -a items <<< "$(dot_visible_children "$current")"
    if [[ "@{#items[@]}" -eq 0 ]]; then return 0; fi
    if [[ "$selected" -ge "@{#items[@]}" ]]; then selected=0; fi

    dot_render_multi_menu "$current" "$selected" "$title" "$subtitle"
    key="$(dot_read_key)" || return 1

    case "$key" in
      $'\\e[A') if [[ "$selected" -gt 0 ]]; then selected=$((selected - 1)); fi ;;
      $'\\e[B') if [[ "$selected" -lt $((@{#items[@]} - 1)) ]]; then selected=$((selected + 1)); fi ;;
      $'\\e[D'|b|B) return 2 ;;
      q|Q) return 1 ;;
      " ") id="@{items[$selected]}"; dot_toggle_multi_item "$id" ;;
      "") return 0 ;;
    esac
  done
}

dot_run_step() {
  local flow="$1" step="$2" step_index="$3" step_total="$4"
  local mode="@{DOT_MODES[$step]:-multi}"
  local title="dot > @{DOT_LABELS[$flow]}"
  local subtitle=""
  subtitle="步骤 @{step_index}/@{step_total}: @{DOT_LABELS[$step]}"

  dot_render_flow_progress "$flow" "$step"

  case "$mode" in
    single)
      dot_choose_single "$step" "$title" "$subtitle"
      local result=$?
      if [[ "$result" -eq 0 ]]; then
        dot_select_single_item "$step" "$DOT_CHOICE"
        if [[ "@{DOT_PROMPT_TYPES[$DOT_CHOICE]:-}" == "key" ]]; then
          dot_record_key_prompt "$DOT_CHOICE"
          result=$?
        fi
      fi
      return "$result"
      ;;
    multi)
      dot_choose_multi "$step" "$title" "$subtitle"
      return $?
      ;;
    *)
      dot_choose_multi "$step" "$title" "$subtitle"
      return $?
      ;;
  esac
}

dot_run_flow() {
  local flow="$1"
  local steps=() step index=0 total result
  read -r -a steps <<< "$(dot_visible_children "$flow")"
  total="@{#steps[@]}"

  while [[ "$index" -lt "$total" ]]; do
    step="@{steps[$index]}"
    dot_run_step "$flow" "$step" "$((index + 1))" "$total"
    result=$?
    case "$result" in
      0) index=$((index + 1)) ;;
      2) if [[ "$index" -gt 0 ]]; then index=$((index - 1)); else return 2; fi ;;
      *) return 1 ;;
    esac
  done
  return 0
}

dot_add_with_deps() {
  local id="$1"
  if [[ "@{DOT_PLAN_ADDED[$id]:-0}" == "1" ]]; then
    return 0
  fi

  local dep
  for dep in @{DOT_DEPS[$id]:-}; do
    dot_add_with_deps "$dep"
  done

  DOT_PLAN_ADDED[$id]=1
  if [[ -n "@{DOT_SNIPPET_FUNCS[$id]:-}" ]]; then
    if [[ "@{DOT_POST[$id]:-0}" == "1" ]]; then
      DOT_POST_PLAN+=("$id")
    else
      DOT_PLAN+=("$id")
    fi
  fi
}

dot_build_plan() {
  DOT_PLAN=()
  DOT_POST_PLAN=()
  DOT_PLAN_ADDED=()

  local id leaf
  for id in "@{DOT_ALL_IDS[@]}"; do
    if [[ "@{DOT_SELECTED[$id]:-0}" != "1" ]]; then
      continue
    fi

    if [[ "@{DOT_HIDDEN[$id]:-0}" == "1" ]]; then
      continue
    fi

    if [[ -n "@{DOT_LEAVES[$id]:-}" ]]; then
      for leaf in @{DOT_LEAVES[$id]:-}; do
        dot_add_with_deps "$leaf"
      done
    else
      dot_add_with_deps "$id"
    fi
  done

  DOT_PLAN+=("@{DOT_POST_PLAN[@]}")
}

dot_show_plan() {
  dot_clear_screen
  printf "%bExecution plan%b\\n" "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id index=1
  for id in "@{DOT_PLAN[@]}"; do
    if [[ "@{DOT_POST[$id]:-0}" == "1" ]]; then
      printf " %2d. %s %b(auto)%b\\n" "$index" "@{DOT_LABELS[$id]}" "$DIM" "$NC"
    else
      printf " %2d. %s\\n" "$index" "@{DOT_LABELS[$id]}"
    fi
    index=$((index + 1))
  done

  printf '%s\\n' "────────────────────────────────────────"
}

dot_confirm_plan() {
  if [[ "@{#DOT_PLAN[@]}" -eq 0 ]]; then
    log_warn "No runnable items selected."
    dot_pause
    return 1
  fi

  dot_show_plan
  local answer
  printf "Execute this plan? [y/N] "
  read -r answer
  [[ "$answer" =~ ^[Yy]$ ]]
}

dot_execute_plan() {
  dot_clear_screen
  printf "%bExecuting plan%b\\n" "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id func dep failed_dep status
  for id in "@{DOT_PLAN[@]}"; do
    failed_dep=0
    for dep in @{DOT_DEPS[$id]:-}; do
      if [[ "@{DOT_RESULTS[$dep]:-ok}" == "failed" || "@{DOT_RESULTS[$dep]:-ok}" == "skipped" ]]; then
        failed_dep=1
        break
      fi
    done

    if [[ "$failed_dep" == "1" ]]; then
      DOT_RESULTS[$id]="skipped"
      log_warn "Skipped @{DOT_LABELS[$id]} because a dependency failed"
      continue
    fi

    func="@{DOT_SNIPPET_FUNCS[$id]:-}"
    if [[ -z "$func" ]]; then
      continue
    fi

    log_info "Running @{DOT_LABELS[$id]}"
    "$func"
    status=$?
    if [[ "$status" -eq 0 ]]; then
      DOT_RESULTS[$id]="ok"
      log_ok "@{DOT_LABELS[$id]}"
    else
      DOT_RESULTS[$id]="failed"
      log_error "@{DOT_LABELS[$id]} failed with exit code $status"
    fi
  done
}

dot_print_summary() {
  printf '\\n%bSummary%b\\n' "$BOLD" "$NC"
  printf '%s\\n' "────────────────────────────────────────"

  local id status
  for id in "@{DOT_PLAN[@]}"; do
    status="@{DOT_RESULTS[$id]:-not-run}"
    case "$status" in
      ok) printf " %b✓%b %s\\n" "$GREEN" "$NC" "@{DOT_LABELS[$id]}" ;;
      skipped) printf " %b-%b %s (skipped)\\n" "$YELLOW" "$NC" "@{DOT_LABELS[$id]}" ;;
      *) printf " %b✗%b %s (%s)\\n" "$RED" "$NC" "@{DOT_LABELS[$id]}" "$status" ;;
    esac
  done
}

dot_main() {
  while true; do
    dot_choose_single "__root" "$DOT_TITLE" "@{DOT_DESCRIPTIONS[__root]:-}"
    local result=$?
    case "$result" in
      0) ;;
      *) printf '\\nAborted.\\n'; exit 0 ;;
    esac

    local task="$DOT_CHOICE"
    if [[ "@{DOT_MODES[$task]:-multi}" == "flow" ]]; then
      dot_run_flow "$task"
      result=$?
      if [[ "$result" -eq 2 ]]; then
        continue
      elif [[ "$result" -ne 0 ]]; then
        printf '\\nAborted.\\n'
        exit 0
      fi
    else
      dot_select_single_item "__root" "$task"
    fi

    dot_build_plan
    if dot_confirm_plan; then
      break
    fi
  done

  dot_execute_plan
  dot_print_summary
}
`.replace(/@\{/g, "${");
}

function generateData(
  config: Config,
  allNodes: Map<string, MenuItem>,
  snippetFunctions: Map<string, string>
): string {
  const lines: string[] = [
    `DOT_TITLE=${bashQuote(config.name)}`,
    "declare -a DOT_ALL_IDS=(" + [...allNodes.keys()].map(bashQuote).join(" ") + ")",
    "declare -A DOT_LABELS=()",
    "declare -A DOT_DESCRIPTIONS=()",
    "declare -A DOT_CHILDREN=()",
    "declare -A DOT_DEPS=()",
    "declare -A DOT_LEAVES=()",
    "declare -A DOT_MODES=()",
    "declare -A DOT_HIDDEN=()",
    "declare -A DOT_PROMPT_TYPES=()",
    "declare -A DOT_PROMPT_VARS=()",
    "declare -A DOT_PROMPT_LABELS=()",
    "declare -A DOT_POST=()",
    "declare -A DOT_SNIPPET_FUNCS=()",
    assocAssign("DOT_LABELS", ROOT_ID, config.name),
    assocAssign("DOT_DESCRIPTIONS", ROOT_ID, config.description ?? ""),
    assocAssign("DOT_CHILDREN", ROOT_ID, config.menu.map((item) => item.id).join(" ")),
    assocAssign("DOT_MODES", ROOT_ID, config.menuMode ?? "multi"),
    assocAssign("DOT_HIDDEN", ROOT_ID, "0"),
    assocAssign("DOT_PROMPT_TYPES", ROOT_ID, ""),
    assocAssign("DOT_PROMPT_VARS", ROOT_ID, ""),
    assocAssign("DOT_PROMPT_LABELS", ROOT_ID, ""),
  ];

  for (const [id, node] of allNodes) {
    const children = node.children?.map((child) => child.id).join(" ") ?? "";
    const deps = node.deps?.join(" ") ?? "";
    const leaves = getLeafIds(node).join(" ");

    lines.push(assocAssign("DOT_LABELS", id, node.label));
    lines.push(assocAssign("DOT_DESCRIPTIONS", id, node.description ?? ""));
    lines.push(assocAssign("DOT_CHILDREN", id, children));
    lines.push(assocAssign("DOT_DEPS", id, deps));
    lines.push(assocAssign("DOT_LEAVES", id, leaves));
    lines.push(assocAssign("DOT_MODES", id, node.mode ?? "multi"));
    lines.push(assocAssign("DOT_HIDDEN", id, node.hidden ? "1" : "0"));
    lines.push(assocAssign("DOT_PROMPT_TYPES", id, node.prompt?.type ?? ""));
    lines.push(assocAssign("DOT_PROMPT_VARS", id, node.prompt?.var ?? ""));
    lines.push(assocAssign("DOT_PROMPT_LABELS", id, node.prompt?.label ?? ""));
    lines.push(assocAssign("DOT_POST", id, node.post ? "1" : "0"));

    const func = snippetFunctions.get(id);
    if (func) {
      lines.push(assocAssign("DOT_SNIPPET_FUNCS", id, func));
    }
  }

  return lines.join("\n");
}

function collectPrompts(node: MenuItem): Array<{ var: string }> {
  const prompts: Array<{ var: string }> = [];
  function walk(item: MenuItem) {
    if (item.prompt) {
      prompts.push({ var: item.prompt.var });
    }
    for (const child of item.children ?? []) {
      walk(child);
    }
  }
  walk(node);
  return prompts;
}

function replaceRenderedPromptValue(content: string, varName: string, fallback: string): string {
  if (!fallback) return content;
  const escaped = fallback.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return content.replace(new RegExp(escaped, "g"), `\${DOT_VARS[${varName}]:-${fallback}}`);
}

function generateSnippetFunctions(
  config: Config,
  configDir: string,
  allNodes: Map<string, MenuItem>,
  snippetFunctions: Map<string, string>,
  unresolved: Set<string>
): string {
  const sections: string[] = [];

  for (const [id, node] of allNodes) {
    const func = snippetFunctions.get(id);
    if (!func || !node.script) continue;

    const scriptPath = path.isAbsolute(node.script)
      ? node.script
      : path.resolve(configDir, node.script);
    const mergedVars = { ...config.vars, ...node.vars };
    let scriptContent = loadTemplate(scriptPath, mergedVars, unresolved).trimEnd();
    for (const prompt of collectPrompts(node)) {
      scriptContent = replaceRenderedPromptValue(scriptContent, prompt.var, mergedVars[prompt.var] ?? "");
    }

    sections.push(`# ─── ${node.label} (${node.id}) ───`);
    sections.push(`${func}() {`);
    sections.push(scriptContent);
    sections.push("}");
  }

  return sections.join("\n\n");
}
